---
- hosts: centos
  become: yes
  tasks:
   - name: apache
     yum: name=httpd state=latest
   - name: start httpd
     service: name=httpd enabled=yes state=started
   - name: install index
     template:
       src: index.php
       dest: /var/www/html/index.php
