---
- hosts: centos
  become: yes
  tasks:
   - name: install httpd
     yum: 
       name=httpd 
   - name: install php
     yum:
       name: [ 'php', 'php-mysql', 'php-pdo', 'php-gd','php-mbstring' ]
     service:
       name: httpd
       state: restarted
  
