---
- hosts: centos
  become: yes
  tasks:
   - name: install httpd
     yum: 
       name=httpd 
   - name: install php
     yum:
       name: [ 'php', 'php-mysql', 'php-pdo', 'php-gd','php-mbstring' ]
     service:
       name: httpd
       state: restarted
   - name: file copying
     copy: 
      src: /home/ansible/index.php
      dest: /var/www/html/index.php
      mode: 0755
